In [11]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import PCA

In [12]:
df=pd.read_csv('heart.csv')
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [13]:
df.shape

(918, 12)

In [14]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [16]:
X = df.drop("HeartDisease",axis=1)
y = df.HeartDisease

In [17]:
encoder=LabelEncoder()
X['Sex']=encoder.fit_transform(X['Sex'])
X['ChestPainType']=encoder.fit_transform(X['ChestPainType'])
X['RestingECG']=encoder.fit_transform(X['RestingECG'])
X['ExerciseAngina']=encoder.fit_transform(X['ExerciseAngina'])
X['ST_Slope']=encoder.fit_transform(X['ST_Slope'])
X

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,1,1,140,289,0,1,172,0,0.0,2
1,49,0,2,160,180,0,1,156,0,1.0,1
2,37,1,1,130,283,0,2,98,0,0.0,2
3,48,0,0,138,214,0,1,108,1,1.5,1
4,54,1,2,150,195,0,1,122,0,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1
914,68,1,0,144,193,1,1,141,0,3.4,1
915,57,1,0,130,131,0,1,115,1,1.2,1
916,57,0,1,130,236,0,0,174,0,0.0,1
917,38,1,2,138,175,0,1,173,0,0.0,2

In [18]:
scaler=StandardScaler()
X=scaler.fit_transform(X)
X=pd.DataFrame(X)
X

,0,1,2,3,4,5,6,7,8,9,10
0,-1.433140,0.515952,0.229032,0.410909,0.825070,-0.551341,0.017255,1.382928,-0.823556,-0.832432,1.052114
1,-0.478484,-1.938163,1.275059,1.491752,-0.171961,-0.551341,0.017255,0.754157,-0.823556,0.105664,-0.596078
2,-1.751359,0.515952,0.229032,-0.129513,0.770188,-0.551341,1.601219,-1.525138,-0.823556,-0.832432,1.052114
3,-0.584556,-1.938163,-0.816995,0.302825,0.139040,-0.551341,0.017255,-1.132156,1.214246,0.574711,-0.596078
4,0.051881,0.515952,1.275059,0.951331,-0.034755,-0.551341,0.017255,-0.581981,-0.823556,-0.832432,1.052114
...,...,...,...,...,...,...,...,...,...,...,...
913,-0.902775,0.515952,2.321086,-1.210356,0.596393,-0.551341,0.017255,-0.188999,-0.823556,0.293283,-0.596078
914,1.536902,0.515952,-0.816995,0.627078,-0.053049,1.813758,0.017255,0.164684,-0.823556,2.357094,-0.596078
915,0.370100,0.515952,-0.816995,-0.129513,-0.620168,-0.551341,0.017255,-0.857069,1.214246,0.293283,-0.596078
916,0.370100,-1.938163,0.229032,-0.129513,0.340275,-0.551341,-1.566710,1.461525,-0.823556,-0.832432,-0.596078
917,-1.645286,0.515952,1.275059,0.302825,-0.217696,-0.551341,0.017255,1.422226,-0.823556,-0.832432,1.052114

In [19]:
X.columns=['Age','Sex','ChestPainType','RestingBP','Cholesterol','FastingBS','RestingECG','MaxHR','ExerciseAngina','Oldpeak','ST_Slope']
X

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,-1.433140,0.515952,0.229032,0.410909,0.825070,-0.551341,0.017255,1.382928,-0.823556,-0.832432,1.052114
1,-0.478484,-1.938163,1.275059,1.491752,-0.171961,-0.551341,0.017255,0.754157,-0.823556,0.105664,-0.596078
2,-1.751359,0.515952,0.229032,-0.129513,0.770188,-0.551341,1.601219,-1.525138,-0.823556,-0.832432,1.052114
3,-0.584556,-1.938163,-0.816995,0.302825,0.139040,-0.551341,0.017255,-1.132156,1.214246,0.574711,-0.596078
4,0.051881,0.515952,1.275059,0.951331,-0.034755,-0.551341,0.017255,-0.581981,-0.823556,-0.832432,1.052114
...,...,...,...,...,...,...,...,...,...,...,...
913,-0.902775,0.515952,2.321086,-1.210356,0.596393,-0.551341,0.017255,-0.188999,-0.823556,0.293283,-0.596078
914,1.536902,0.515952,-0.816995,0.627078,-0.053049,1.813758,0.017255,0.164684,-0.823556,2.357094,-0.596078
915,0.370100,0.515952,-0.816995,-0.129513,-0.620168,-0.551341,0.017255,-0.857069,1.214246,0.293283,-0.596078
916,0.370100,-1.938163,0.229032,-0.129513,0.340275,-0.551341,-1.566710,1.461525,-0.823556,-0.832432,-0.596078
917,-1.645286,0.515952,1.275059,0.302825,-0.217696,-0.551341,0.017255,1.422226,-0.823556,-0.832432,1.052114

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [22]:
lr=LogisticRegression()

In [23]:
lr.fit(X_train,y_train)

LogisticRegression()

In [24]:
lr.score(X_test,y_test)

0.8315217391304348

In [25]:
lr.score(X_train,y_train)

0.8583106267029973

APPLYING PCA

In [42]:
pca=PCA(n_components=5)

In [43]:
X2=pca.fit_transform(X)

In [44]:
X2.shape

(918, 5)

In [50]:
pca.components_

array([[ 0.33103837,  0.21514873, -0.28988854,  0.16639177, -0.16381331,
         0.19767972,  0.10647551, -0.40472098,  0.4232788 ,  0.36192709,
        -0.42567441],
       [-0.08085543,  0.26772334, -0.01860578, -0.27034354, -0.59881255,
         0.33763486,  0.40079525, -0.17101247, -0.17139804, -0.3674351 ,
         0.14667344],
       [ 0.50895006, -0.21490295,  0.42425764,  0.52287475, -0.06198275,
         0.3874847 , -0.03700889, -0.0319887 , -0.26251048, -0.08210432,
         0.09675717],
       [ 0.0036913 ,  0.22050904,  0.23827689, -0.3910541 , -0.18084955,
         0.35273428, -0.61369557,  0.2453597 , -0.12252194,  0.20874208,
        -0.29854046],
       [ 0.14888066, -0.82883491, -0.17052517, -0.43004644, -0.10371743,
         0.09130452,  0.01281995, -0.1666085 , -0.04456874, -0.01279769,
        -0.1663783 ]])

In [53]:
pca.explained_variance_

array([2.76837877, 1.46557436, 1.15768153, 1.00087542, 0.8717934 ])

In [52]:
pca.explained_variance_ratio_

array([0.25139665, 0.1330889 , 0.10512913, 0.09088956, 0.07916761])

In [45]:
X2_train,X2_test,y_train,y_test=train_test_split(X2,y,test_size=0.2,random_state=47)

In [46]:
lr=LogisticRegression(max_iter=1000)

In [47]:
lr.fit(X2_train,y_train)

LogisticRegression(max_iter=1000)

In [48]:
lr.score(X2_test,y_test)

0.8206521739130435

In [49]:
lr.score(X2_train,y_train)

0.8542234332425068